### ISSUE TITLE
Can't load `constants`

### ISSUE THREAD

**Issue by mockdeep** [patrick-steele-idem/app-module-path-node#14]
Not sure if this is an issue here or elsewhere, but I can't load a file in our application called `constants`. It instead seems to load something maybe out of node core:

```js
var Constants = require('constants');
console.log('constants: ', Constants);
```

Result, not our constants:

```
constants:  { E2BIG: 7,
  EACCES: 13,
  EADDRINUSE: 98,
  EADDRNOTAVAIL: 99,
  EAFNOSUPPORT: 97,
  EAGAIN: 11,
  EALREADY: 114,
  EBADF: 9,
  EBADMSG: 74,
  EBUSY: 16,
  ECANCELED: 125,
  ECHILD: 10,
  ECONNABORTED: 103,
  ECONNREFUSED: 111,
  ECONNRESET: 104,
  ...
```

Other files I require from my application seem to be fine, though, so not sure what the deal is with this one. We only have one file named `constants.js` in our project, and don't have any `constants` folder in our `node_modules`.

**Comment by patrick-steele-idem** [comment]
app-module-path will add a search path to the end of the Node.js module search path. If you have an application-level module that has an overlapping name with a native Node.js module or an installed module then the native or installed Node.js module will be found first.

In the docs for `app-module-path` we make the following recommendation:

> Since this module changes the Node.js convention of how non-relative modules are resolved, it is recommended (but not required) to put all app modules in a common directory below the application root (such as `my-app/src` or `my-app/app_modules`) and then to add the application root to the search path. The require calls would then be something like `require('src/foo')` or `require('app_modules/foo')`. The common prefix makes it more clear that the module can be found in the application's modules directory and not in the `node_modules` directory.

If you followed that recommendation then your code would be the following:

```javascript
var Constants = require('src/constants');
console.log('constants: ', Constants);
```

Right now you have a `require` call that looks like it could be a require for an installed module or a native module. Hence the problem. I would strongly recommend updating your code to follow the recommendation
