### ISSUE TITLE
Can't find `package.json`

### ISSUE THREAD

**Issue by rjhilgefort** [patrick-steele-idem/app-module-path-node#18]
Everything works great, but I can't seem to require `package.json` from anywhere after requiring 'app-module-path'. Am I missing something about the usage? I'm able to get other files from the root directory of the path, as well as things nested in sub-folders.

Any help would be appreciated.

**Comment by patrick-steele-idem** [comment]
Can you please provide more details?:

- Which directory you are adding to the module search path
- Directory structure
- Stack trace
- etc.

**Comment by rjhilgefort** [comment]
Yeah, sure, thanks for the response. I was adding project root from a sub-directory (see below).

Here's the project structure, and how I'm using it. You can see in the top buffer that I'm adding the parent directory (root of project) to the tree (`src/app.js`). In the bottom buffer, you can see me trying to source the `package.json`.

![screen shot 2016-06-03 at 11 59 14](https://cloud.githubusercontent.com/assets/2034823/15784917/aec6d012-2982-11e6-89bb-de85c78c6981.png)

Stack trace of error: 

![screen shot 2016-06-03 at 12 02 08](https://cloud.githubusercontent.com/assets/2034823/15784989/0cf1d8d0-2983-11e6-806e-4e5c04456310.png)

**Comment by patrick-steele-idem** [comment]
Thanks for the details. I created a simple project with a similar directory and was not able to reproduce :(

Do you think you could created a trimmed down version of your project to reproduce the problem?

**Comment by rjhilgefort** [comment]
hmm, I'll play with it then and get back to you. Thanks for trying to reproduce. It could be something in my build process.

**Comment by rjhilgefort** [comment]
My build process was a bit convoluted and the solution was as simple as making sure the `package.json` was injected into mu build directory properly. Thanks for the quick response and the help!
