### ISSUE TITLE
require node_modules before try to require local files

### ISSUE THREAD

**Issue by oxala** [patrick-steele-idem/app-module-path-node#20]
I found an unexpected (as i believe) behavior:

If i have a file like 'marko.json' in my project root folder;
After i add project root folder to 'app-module-path'. Next time i `require('marko')` it will return the `marko.json` contents instead of the marko node_module;

**Comment by singggum3b** [comment]
should'nt the require order be optional? In my case , i want in dev environment , let the `sub_module` folder take higher priority. I had to use v1.1.0 to have this behavior
