### ISSUE TITLE
Mocha OPTS

### ISSUE THREAD

**Issue by rochapablo** [patrick-steele-idem/app-module-path-node#5]
How can I include the module on Mocha config file (mocha.opts)?

```
-r, --require <name>                    require the given module
```

This will not work
```
--require('app-module-path').addPath('../');
```

This will work, but how to define the root?
```
--require app-module-path
```

**Comment by rochapablo** [comment]
I'm not sure if this is the right thing, but take a look at what I did:

app/test/mocha.opts
```
--require test/bootstrap.js
--recursive
```

app/test/bootstrap.js
```
var path = require('path');
require('app-module-path').addPath(path.resolve());
```

app/test/my-module
```
require('my-module/my-file.js');
```

Where my folders are:
```
- app
  - my-module
    - js files...
- test
  - my-module
    - js files...
```

**Comment by patrick-steele-idem** [comment]
Hi @rochapablo, I think what you did looks great. I'll have to use that trick in my projects. I'm closing the issue because I like your solution, but let me know if you still think we should make changes to `app-module-path`. Thanks for sharing your solution.

**Comment by rochapablo** [comment]
Thank you @patrick-steele-idem.

**Comment by nekman** [comment]
Nice solution @rochapablo, it worked like a charm!

**Comment by araujo-luis** [comment]
What if I want to require modules from the `app` folder into my `test` folder. it didn't work for me :/
