### ISSUE TITLE
Doesn't work with 'imports'?

### ISSUE THREAD

**Issue by delenius** [patrick-steele-idem/app-module-path-node#9]
I am trying to use this along with mocha. My setup looks something like this:

src/js/... lots of files
test/   ... tests

When I compile things, I give src/js as a base dir to browserify, so all the imports in files in src/js use absolute paths starting at src/js. So, I need to have the same base dir (src/js) set up in the tests.

The problem is that, when I have imports in my test files, they seem to be hoisted to the top, so they run before the addPath command can run. If I use "require" to import stuff into a top-level test file, then it works. So, this is not a big deal, but slightly annoying. Is there any way around this, or a recommended aproach? Perhaps you should point this out in the README, at least.

**Comment by patrick-steele-idem** [comment]
Hey @delenius, another developer submitted a PR to support enabling `app-module-path` using the `import` keyword as shown below:

```javascript
import "app-module-path/register";
```

If you use that method to enable `app-module-path` then you should not need to worry about issues with hoisting. Please let me know if that works for you. Thanks.

**Comment by delenius** [comment]
The problem is that that only adds the current directory. I want to add a *different* directory.

**Comment by patrick-steele-idem** [comment]
I see. Here's what I recommend then. Create another file named `app-module-path-register.js` and inside that module use `app-module-path` to add the desired path path (no other code, so that you don't have to worry about hoisting). Then, just add `import "./app-module-path-register"` at the top of your test files (as the first import). That should do the trick.

**Comment by delenius** [comment]
That works beautifully, thanks! :thumbsup:

I also like how it separates the added paths into a separate file.

**Comment by patrick-steele-idem** [comment]
Great. Glad that worked for you!
